### ISSUE TITLE
Modding tools

### ISSUE THREAD

**Issue by emoose** [emoose/OutRun2006Tweaks#90]
Would probably be good to start a thread for any useful mod tools, feel free to link to any tools useful for OR2 here, or talk about using tools with the game.

#### General tools
- [offzip](https://aluigi.altervista.org/mytoolz/offzip.zip) - can be used to decompress most of games .SZ files via `mkdir output; offzip -a filename.sz output` (some SZ files might not decompress properly though, not really sure why)
- [010 Editor](https://www.sweetscape.com/010editor/) - great hex editor, can use templates that give names/structures to the bytes in a file, rather than needing to stare at hex digits all day, lots of templates available for common file types too.
- [procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) - can be used to see what files / IP addresses that the game tries to access
- [Cheat Engine 7.5](https://www.reddit.com/user/ChucksFeedAndSeed/comments/12usdd5/cheat_engine_75_adfree_installer/) - can be used to inspect memory addresses & also mess with the games code, the ad-free/malware-free version is linked, to install it properly run the following using command-prompt `CheatEngine75.exe /VERYSILENT /ZBDIST`

#### OutRun2 Tools
- [Outrun2Tool](https://github.com/emoose/OutRun2006Tweaks/issues/75#issuecomment-2244498483) - tool for unpacking/repacking C2C SZ files, right now it can extract sprite SZ files into dds files & XML for the atlas info, and also repack updated atlas, maybe PMT model support in future as well.
- [or2-tools (JayFoxRox)](https://github.com/JayFoxRox/or2-tools) - Python scripts for working with several file formats, seems mostly built for OR2 Xbox but some support for C2C is added
- [or2-tools (Sonic-TV)](https://github.com/Sonic-TV/or2-tools) - fork of the above, I think C2C support is meant to be improved but the repo currently matches JayFoxRox version, hopefully update soon 🙏 
- [OutrunX](https://forum.arcadecontrols.com/index.php/topic,130891.msg1347631.html#msg1347631) - tool by Howard that can use offzip to decompress & then split DDS files from some SZ files (though some SZ's contain textures that are missing DDS headers, which the tool won't work with)

**Comment by envido32** [comment]
Oh this is truly amazing, thank you so much! This is so handy!

btw, there was a newer [OutrunX v2.2](https://forum.arcadecontrols.com/index.php/topic,147131.msg1531351.html#msg1531351) than the link you shared.

And not exactly a tool but there was a [Course Editor](https://forum.arcadecontrols.com/index.php/topic,130891.msg1681494.html#msg1681494) in development at one point, I think this is the only alpha release available but it's still interesting to test.

**Comment by Tenome** [comment]
The course editor is fun, unfortunately it doesn't support hacking in 15+15 courses for the true endurance test since I think you'd have to change the level table to support that as well.

**Comment by lance8765** [comment]
The true endurance test would be 30+30 (Normal and Reverse) lmao.

**Comment by Tenome** [comment]
Are the flags for hitting checkpoints easy to find? I might want to try and make a LiveSplit for AutoSplitter later, which requires finding the memory addresses to watch.

**Comment by envido32** [comment]
> Are the flags for hitting checkpoints easy to find? I might want to try and make a LiveSplit for AutoSplitter later, which requires finding the memory addresses to watch.

I just tested CheatEngine for the fist time with [Howard's CT files ](https://forum.arcadecontrols.com/index.php/topic,130891.msg1682245.html#msg1682245)and to be honest is much more than I can chew... 

But it seems to be hidden here somewhere

![image](https://github.com/user-attachments/assets/c077e5b2-8104-4ede-8e48-8037bb8912e0)

**Comment by Tenome** [comment]
Damn, I wished I checked Github first lol. I just wasted two hours scanning trying to find the value, thinking it might be a unique flag that was calculating the time difference, when I could have just used that CT table which already has what I think I need ("stages passed" and "actual stage number" that simply go up by one). Oh well, at least I was getting through my backlog of music the entire time and found some more songs to add to the CD switcher.

**Comment by envido32** [comment]
> Damn, I wished I checked Github first lol. I just wasted two hours scanning trying to find the value, thinking it might be a unique flag that was calculating the time difference, when I could have just used that CT table which already has what I think I need ("stages passed" and "actual stage number" that simply go up by one). Oh well, at least I was getting through my backlog of music the entire time and found some more songs to add to the CD switcher.
> 
> Edit: Hm, it's a start. Hitting the last goal doesn't actually increase it, though, so I have to figure out what to do with that. I'm trying to lock the timer and see which value the "Time Elapsed" address (007D39DC 4 byte) equals the checkpoint time, but I can't seem to actually freeze the timer when I check it off. It's always increasing by a split second before snapping back down to the value I set.

If you have more experience with CE Howard left a lot of useful information in that threat, [from page 26 to 29 he](http://forum.arcadecontrols.com/index.php/topic,130891.msg1680214.html#msg1680214) explains how he found the stages files, made a lookup table and how they are connected. He event talks about what type of bugs or limitations he stumble-upon, very interesting stuff.

I wish I'll be able to give it a use soon, but my technical level is years behind. The track editor randomize sounded amazing to try but it seems that it was never released as far as I'm aware :(

**Comment by emoose** [comment]
OR2Tool 0.1.2
- Hopefully fixed issue with exported DDS files not being padded out, which stopped texconv working with them
- Adds support for exporting JSON atlas files which can be opened in [Atlased](https://witnessmonolith.itch.io/atlased):

![image](https://github.com/user-attachments/assets/0bd073cf-d714-4747-9245-26213d35ee3a)

`texture_X_atlas.json` files will be exported to same folder as info.xml/texture_X.dds/etc.

You'll need to convert the DDS texture to png first (`texconv -ft png texture_X.dds`) and then flip it vertically, after that Atlased should be able to load the texture_X_atlas.json file for you.

There's no support for reading in updated atlas JSONs yet, but the sprite_XXX numbers shown in Atlased do match the XML's `<Sprite Index="XXX">`, so you could update the XML yourself using the values from Atlased (note that XML expects end X/Y, not size which Atlased shows - just add the position + size from Atlased to get the end)

**Comment by emoose** [comment]
OR2Tool 0.1.3: [OR2Tool-0.1.3.zip](https://github.com/user-attachments/files/16434759/OR2Tool-0.1.3.zip)

- now reads in json atlas files when updating the XST, so you can use Atlased to edit the atlas and save your changes now
- will try to convert DDS to PNG & flip it vertically automatically, so you can just load JSON straight into Atlased now - hopefully the decoders are right for all the formats, if you notice any broken PNG with it please let me know.

**Comment by Sonic-TV** [comment]
I guess atlas modding is kinda needed for multilingual texts.
Some of the texts are just squeezing for fitting in the atlases.
(Example: "position" on vs mode has a narrower spacing comparing to other texts.)

**Comment by Tenome** [comment]
We learned that if you use FXT Course Editor to make a custom mixed (2 + SP + Reversed) layout, vanilla players can still join the lobby and run the intended tracks (with the exception of Dusk/Night stages, which get switched to their regular variants). However, the vanilla players will disappear from the modded players and vice versa when they change to the next track. Something to keep in mind if we ever get official custom track order support down the line. I believe Howard was working on that for his next FXT Editor update, which would have put a new menu for each custom track order in the in-game menu.

**Comment by emoose** [comment]
Kinda got texture extraction working for Online Arcade, mostly matched C2C texture format but they switched some Xbox structs to X360 ones, and also used X360 tiled swizzling too...

Sadly haven't found any textures that are actually higher res than C2C yet, maybe there's some that are less crispy though, I'll see if I can push a OR2Tool update for it soon.

Have any Online Arcade players noticed any better textures in there? IIRC S0L did mention it might have some higher quality things, maybe he just meant the car models/shaders though.

**Comment by Sonic-TV** [comment]
I guess you can add supports for GZ files used in SDX now...

**Comment by emoose** [comment]
Looks like SDX GZ are normal gzip files but with a 0xB header "or2 2099304 " / `6F 72 32 20 32 30 39 39 33 30 34 20`
If you delete those 0xB bytes, you can use "gzip -d spr_XXX.gz" to decompress to spr_XXX file
Then to recompress you can use "gzip -k spr_XXX" to create spr_XXX.gz, then add those 0xB bytes to the beginning

**Comment by Sonic-TV** [comment]
> Looks like SDX GZ are normal gzip files but with a 0xB header "or2 2099304 " / `6F 72 32 20 32 30 39 39 33 30 34 20` If you delete those 0xB bytes, you can use "gzip -d spr_XXX.gz" to decompress to spr_XXX file Then to recompress you can use "gzip -k spr_XXX" to create spr_XXX.gz, then add those 0xB bytes to the beginning
> 
> Maybe will see if I can add extraction support to or2tool for them soon

Thanks. Or you can make the tool pack the sprites in XST format as they are just pure XSTs inside of them.

**Comment by Tenome** [comment]
> OR2Tool 0.1.3: [OR2Tool-0.1.3.zip](https://github.com/user-attachments/files/16434759/OR2Tool-0.1.3.zip)

Has anyone tried scaling the json's expected coordinates to accommodate larger spritesheets to make alignment easier? Can I just multiply them?

**Comment by Sonic-TV** [comment]
bugs here:
if you extract SZ files in Outrun Online Arcade, the following error occurs.
`D:\Outrun Online Arcade\X360-ALL>or2tool .\sprite\spr_SPRANI_CLAR_RANK_Fxst.sz
Decompressing XST...
Reading XST...
Unhandled exception. System.ArgumentOutOfRangeException: count ('-1572864') must be a non-negative value. (Parameter 'count')
Actual value was -1572864.
   at System.ArgumentOutOfRangeException.ThrowNegative[T](T value, String paramName)
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at OutRun2Tool.XST.Read(IO io)
   at OutRun2Tool.Program.Main(String[] args)`

**Comment by emoose** [comment]
Yeah arcade uses slightly diff format, did get something working for it at https://github.com/emoose/OutRun2006Tweaks/issues/90#issuecomment-2308370823 but changing code broke it for PC, I'll see if I can add some OA mode to it soon.

IIRC the textures weren't much different to PC though, at least the UI sprites anyway, not sure if track/car textures might have been changed.

**Comment by Sonic-TV** [comment]
> Yeah arcade uses slightly diff format, did get something working for it at [#90 (comment)](https://github.com/emoose/OutRun2006Tweaks/issues/90#issuecomment-2308370823) but changing code broke it for PC, I'll see if I can add some OA mode to it soon.
> 
> IIRC the textures weren't much different to PC though, at least the UI sprites anyway, not sure if track/car textures might have been changed.

I'll wait then. Can your tool extract XMTs and BINs(used on models and courses), btw?

**Comment by nhasa01** [comment]
Is it possible to add more elements ingame? I wanted to add more Ferrari cars but without taking away the ones that already exist in the game. I would also like to add more country flags without removing the ones that already exist in the game, as I have just changed the flag of Thailand to add the flag of my Brazil. It would be nice to be able to add the flags of all the countries in the world.
![image](https://github.com/user-attachments/assets/9e7b2649-e223-4be2-a5be-7435a8274e7d)

**Comment by Tenome** [comment]
Actual modding is outside the scope of Tweaks, we won't be getting any new cars, etc.

**Comment by envido32** [comment]
> ## Convert Atlas.json to SVG
> 
> It would be interesting if we had a tool that could convert exported OR2 atlas (like for example: BF3EE5C6_512x512_atlas.json) to a SVG vector image with the same dimensions with its rectangle areas. It would be easier to remaster textures with precision. I'm doing by hand using [Atlased](https://witnessmonolith.itch.io/atlased) tool and getting its parameters and drawing them in InkScape / Illustrator.
> 
> This is what I'm doing: ![BF3EE5C6_512x512-atlas](https://private-user-images.githubusercontent.com/8125662/396600643-420c8447-fc39-43ab-b0f5-70dd24e79aaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDQ5OTQsIm5iZiI6MTczNTA0NDY5NCwicGF0aCI6Ii84MTI1NjYyLzM5NjYwMDY0My00MjBjODQ0Ny1mYzM5LTQzYWItYjBmNS03MGRkMjRlNzlhYWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjRUMTI1MTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQ1NTlhNzVlZmY2YzY4OTUwMjhhNzc0NWE0ZTE2MzIyNzZiYTY0M2JkMzY2OWVmZDIwODQ2NTMwZDQwNjhmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.aXxZBXlGJHsF8oCctY9AX0eyBk8ZUZa0GuGKfknpBoc)
> 
> I tried to automate the process creating a script, but as I'm not a developer I couldn't get it working. I worked with the AI Gemini from Google and it generated this script "atlas2svg.ps1", a Windows PowerShell Script:
> 
> ```
> 
> # OutRun2006Tweaks Convert Atlas.json to SVG Windows PowerShell Script
> # atlas2svg.ps1 - Version 1.2 - 20241217
> 
> # Instructions
> # 1) Navigate to the directory where the script and your JSON file are located.
> # 2) Execute the script with the JSON file name as an argument:
> # 3) .\atlas2svg.ps1 HASHID_WITDHxHEIGHT_atlas.json
> 
> # Attempt to load System.Management.Automation module 
> Import-Module Microsoft.PowerShell.Management -Force # Might require administrator privileges
> 
> # Get the JSON file name from the command line argument
> $jsonFile = $args[0]
> 
> # Extract dimensions and base name from the filename
> $filenameRegex = '^(.+?)_(\d+)x(\d+)_atlas\.json$'
> $match = $jsonFile -match $filenameRegex
> 
> if ($match) {
>   $width = $matches[2]
>   $height = $matches[3]
>   $baseName = $matches[1]
> 
>   # Get the directory path of the JSON file
>   $jsonDir = Split-Path $jsonFile
> 
>   # Check if directory path is valid
>   if ($jsonDir) {
>     $svgFile = Join-Path $jsonDir "$baseName.svg"
>     Write-Host "Saving SVG to: $svgFile"
>   } else {
>     Write-Warning "Unable to determine output directory. Using current directory."
>     $svgFile = "$baseName.svg"
>   }
> } else {
>   Write-Warning "Invalid filename format. Please use HASHID_WITDHxHEIGHT_atlas.json"
>   exit 1
> }
> 
> # Use ConvertFrom-Json to parse the JSON data
> $jsonData = ConvertFrom-Json -InputObject (Get-Content $jsonFile)
> 
> # Create a new SVG file
> $svg = New-Object System.Xml.XmlDocument
> $svg.AppendChild($svg.CreateElement("svg"))
> $svg.DocumentElement.SetAttribute("width", $width)
> $svg.DocumentElement.SetAttribute("height", $height)
> $svg.DocumentElement.SetAttribute("xmlns", "http://www.w3.org/2000/svg")
> 
> # Add rectangles to the SVG (modify based on your JSON data structure)
> foreach ($region in $jsonData.regions) {
>   $rect = $svg.CreateElement("rect")
>   $rect.SetAttribute("x", $region.rect[0])
>   $rect.SetAttribute("y", $region.rect[1])
>   $rect.SetAttribute("width", $region.rect[2])
>   $rect.SetAttribute("height", $region.rect[3])
>   $rect.SetAttribute("fill", "blue")  # Adjust fill color as needed
>   $svg.DocumentElement.AppendChild($rect)
> }
> 
> # Save the SVG file
> $svg.Save($svgFile)
> ```
> 
> After running the script in the same path as the JSON through Windows PowerShell like this: ".\atlas2svg.ps1 HASHID_WITDHxHEIGHT_atlas.json"
> 
>     1. It would detect the filename and it would define the SVG artboard dimensions from it;
> 
>     2. then it would get the rectangle objects with its dimensions and coordinates, and draw them into a SVG file;
> 
>     3. This file would have the same name as the JSON but with the SVG extension, in the same path where the JSON is located.
> 
> 
> The problem is I got lots of errors, I tried to manipulate the fixes with Gemini and event then it couldn't fix the script. _I tried to run it with Administrator privileges in Windows 10 FYI._ Does someone have the knowledge to fix this script our make a better tool?
> 
> The JSON that I'm using to test the script was downloaded from https://github.com/Sonic-TV/OR2006Sprites/ [BF3EE5C6_512x512_atlas.json](https://github.com/user-attachments/files/18169317/BF3EE5C6_512x512_atlas.json)

Done! 

I made a simple Python3 script that reads the atlas.json and makes the .svg files 

You can find the script it here:

https://github.com/Sonic-TV/OR2006Sprites/blob/main/Original%20(PC)/json2svg/json2svg.py

And the generated SVGs on the Sonic-TV Textures PC dump folders, here is an example:

https://github.com/Sonic-TV/OR2006Sprites/blob/main/Original%20(PC)/Original%20(Tweaks%20dumps)/spr_sprani_game_cvt_Exst/36895E6C_256x512.svg

**Comment by Zoukambada** [comment]
Thank you @envido32 ! This worked flawlessly with the texture that I was working on!
Finally I can check precisely if the sprite is fitting properly at his boundaries.

![image](https://github.com/user-attachments/assets/03a7f9c7-0a33-47e0-99ea-2b36faaba994)

**Comment by Darktreivor** [comment]
@emoose can you help me to understante texture in C2C ps2 version? I extract the sprit and decompress .sz files, but i try extract texture usando OR2tool nothing happend. I'm localizing this game for Brazilian Portuguese. 

[bloco_33_unpack.zip](https://github.com/user-attachments/files/19838161/bloco_33_unpack.zip)
